"""Kivy recipe: config.pxi for headless CI (extends p4a CythonRecipe)."""
import os

from pythonforandroid.recipes.kivy import KivyRecipe as _BaseKivyRecipe

_CONFIG_PXI = """# Autogenerated for CI
DEF PY3 = 1
DEF USE_OPENGL_ES2 = 1
DEF USE_OPENGL_MOCK = 0
DEF USE_GLEW = 0
DEF USE_SDL2 = 1
DEF USE_PANGOFT2 = 0
DEF USE_IOS = 0
DEF USE_ANDROID = 1
DEF USE_MESAGL = 0
DEF USE_X11 = 0
DEF USE_WAYLAND = 0
DEF USE_GSTREAMER = 0
DEF USE_AVFOUNDATION = 0
DEF USE_OSX_FRAMEWORKS = 0
DEF DEBUG_GL = 0
DEF KIVY_SDL_GL_ALPHA_SIZE = 8
DEF DEBUG = 0
DEF PLATFORM = "android"
"""


class KivyRecipe(_BaseKivyRecipe):
    def download(self, arch):
        super().download(arch)
        self._write_config_pxi(arch)

    def prepare_build_dir(self, arch):
        super().prepare_build_dir(arch)
        self._write_config_pxi(arch)

    def prebuild_arch(self, arch):
        self._write_config_pxi(arch)
        super().prebuild_arch(arch)

    def build_arch(self, arch):
        self._write_config_pxi(arch)
        super().build_arch(arch)

    def _write_config_pxi(self, arch):
        build_dir = self.get_build_dir(arch.arch)
        paths = [
            os.path.join(build_dir, "kivy", "include", "config.pxi"),
            os.path.join(build_dir, "include", "config.pxi"),
        ]
        for path in paths:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(_CONFIG_PXI)


recipe = KivyRecipe()
